### ISSUE TITLE
关于 lock_manager 中事务隔离级别的支持问题？

### ISSUE THREAD

**Issue by pedrogao** [Sorosliu1029/Database-Systems#1]
Hi，楼主你好，我在实现 lock_manager 的时候，遇到了一些疑惑，参考了一下你的代码，但还是没有理解。

对于 [LockShared](https://github.com/Sorosliu1029/Database-Systems/blob/2fc1edd1ddc55ded094000e575f20b1518c4b949/src/concurrency/lock_manager.cpp#L28) 这个方法，即当事务来请求一个 RID 的读锁时，为什么判断事务隔离级别是 READ_UNCOMMITTED 时会直接 abort 了？

在我的理解里，读未提交，应该是最低的级别，不用去解决任何脏读问题，可是这里直接返回了，不就证明了 LockManager 保证了在读未提交状态，RID 仍然只有一个事务能够持有，仍然保证了 RID 的数据安全性，这和直观上的理解不一致，请问楼主是如何理解的，望回复，多谢了～

**Comment by Sorosliu1029** [comment]
这里是一个先后顺序的问题，即：READ_UNCOMMITTED 时，不应该调用 `LockShared`，即不需要加锁

**Comment by pedrogao** [comment]
意思是，在 READ_UNCOMMITTED 事务隔离级别时，无需加锁，因为会出现「脏读」的问题，而加锁，则会解决「脏读」，因此在 READ_UNCOMMITTED 这个级别时，为了保证「脏读」，所以在调用 `LockShared` 时会直接 abort？

**Comment by Sorosliu1029** [comment]
确切的来说，不应该叫「保证脏读」，叫「允许脏读」更准确一些。

具体可以看一个read时的例子，以「sequence read」为例，这里在 READ_UNCOMMITTED 
时，根本不会调用任何 Lock 方法。而对比其他级别，则是需要进行RID上的lock操作的。https://github.com/Sorosliu1029/Database-Systems/blob/2fc1edd1ddc55ded094000e575f20b1518c4b949/src/execution/seq_scan_executor.cpp#L44-L64

**Comment by pedrogao** [comment]
cool，我已经理解了，多谢～
